# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/reversTeam/fizzbuzz-golang
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: make build
      - run: |
          export GO111MODULE=on
          wget http://download.redis.io/redis-stable.tar.gz
          tar xzf redis-stable.tar.gz
          mv redis-stable redis
          cd redis && make
          ./src/redis-server --port 6379 &
          cd -
          ./fizzbuzz-grpc &
          sleep 1
          ./fizzbuzz-http &
          ss -tulw
          go test -v ./...