# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/reversTeam/fizzbuzz-golang
    steps:
      - checkout

      # Install dependencies
      - run: go get -v -t -d ./...

      # Install linter
      - run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.23.1
          wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.23.1
          golangci-lint --version

      # Build binary
      - run: make build

      # Lint the binary and services
      - run: make lint

      # Test run
      - run: |
          export GO111MODULE=on
          wget http://download.redis.io/redis-stable.tar.gz
          tar xzf redis-stable.tar.gz
          mv redis-stable redis
          cd redis && make
          ./src/redis-server --port 6379 &
          cd -
          ./bin/fizzbuzz-grpc &
          sleep 1
          ./bin/fizzbuzz-http &
          ss -tulw
          go test -v ./...