apiVersion: v1
kind: Service
metadata:
  name: fizzbuzz
  labels:
    app: fizzbuzz
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '4242'
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: fb-http-port
  selector:
    app: fizzbuzz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fizzbuzz
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fizzbuzz
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fizzbuzz
    spec:
      containers:
        - name: http
          image: triviere42/fizzbuzz-golang
          command: ["/bin/sh"]
          args: ["-c", "fizzbuzz-http --http-host 0.0.0.0 --exporter-host=0.0.0.0"]
          ports:
            - containerPort: 8080
              name: fb-http-port
        - name: grpc
          image: triviere42/fizzbuzz-golang
          command: ["/bin/sh"]
          args: ["-c", "fizzbuzz-grpc --redis-host redis-master.default.svc.cluster.local"]
          ports:
            - containerPort: 42001
              name: fb-grpc-port
